services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bench-processor:
    build: ./bench_processor
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:5173
      - DATABASE_URL=postgresql+psycopg://appuser:apppass@db:5432/appdb
    volumes:
      - ./bench_processor:/app
    depends_on:
      - db

  bench-react-app:
    build: ./react_app
    ports:
      - "5173:5173"
    depends_on:
      - bench-processor
    volumes:
      - ./react_app:/app
      - /app/node_modules

volumes:
  pgdata: